name: Publish package to the Maven Central Repository
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b
      - name: Publish package ${{github.ref_name}}
        uses: gradle/gradle-build-action@093dfe9d598ec5a42246855d09b49dc76803c005
        with:
          arguments: publish
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
