name: Unit tests

on: push

jobs:
  PostgreSQL:
    name: Unit test on PostgreSQL
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run matrix
        run: echo "${{ matrix.db_version }}"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test
      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'